name: learning_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/orieken/design-patterns-in-dart
author: Rieken <oriekenjr@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: 1.8.0
  test: 1.6.5
